<?php

return [
    'countries' => [
        ['name' => 'United States', 'code' => 'US', 'phone_code' => '+1'],
        ['name' => 'Canada', 'code' => 'CA', 'phone_code' => '+1'],
        ['name' => 'United Kingdom', 'code' => 'GB', 'phone_code' => '+44'],
        ['name' => 'Germany', 'code' => 'DE', 'phone_code' => '+49'],
        ['name' => 'France', 'code' => 'FR', 'phone_code' => '+33'],
        ['name' => 'Nigeria', 'code' => 'NG', 'phone_code' => '+234'],
        ['name' => 'United Arab Emirates', 'code' => 'AE', 'phone_code' => '+971'],
        ['name' => 'India', 'code' => 'IN', 'phone_code' => '+91'],
        ['name' => 'China', 'code' => 'CN', 'phone_code' => '+86'],
        ['name' => 'Japan', 'code' => 'JP', 'phone_code' => '+81'],
        ['name' => 'Brazil', 'code' => 'BR', 'phone_code' => '+55'],
        ['name' => 'South Africa', 'code' => 'ZA', 'phone_code' => '+27'],
        ['name' => 'Australia', 'code' => 'AU', 'phone_code' => '+61'],
        ['name' => 'Mexico', 'code' => 'MX', 'phone_code' => '+52'],
        ['name' => 'South Korea', 'code' => 'KR', 'phone_code' => '+82'],
        ['name' => 'Singapore', 'code' => 'SG', 'phone_code' => '+65'],
        ['name' => 'Netherlands', 'code' => 'NL', 'phone_code' => '+31'],
        ['name' => 'Kenya', 'code' => 'KE', 'phone_code' => '+254'],
        ['name' => 'Ghana', 'code' => 'GH', 'phone_code' => '+233'],
        ['name' => 'Egypt', 'code' => 'EG', 'phone_code' => '+20'],
    ],

    'service_levels' => [
        'domestic_express' => [
            'label' => 'Domestic Express',
            'base_rate' => 48,
            'per_kg_rate' => 7.8,
            'multiplier' => 2.6,
            'transit_days' => 2,
            'is_international' => false,
            'is_active' => true,
        ],
        'international_priority' => [
            'label' => 'International Priority',
            'base_rate' => 85,
            'per_kg_rate' => 7.8,
            'multiplier' => 3.4,
            'transit_days' => 3,
            'is_international' => true,
            'is_active' => true,
        ],
        'freight' => [
            'label' => 'Freight',
            'base_rate' => 220,
            'per_kg_rate' => 7.8,
            'multiplier' => 1.25,
            'transit_days' => 6,
            'is_international' => true,
            'is_active' => true,
        ],
        'overnight' => [
            'label' => 'Overnight',
            'base_rate' => 48,
            'per_kg_rate' => 7.8,
            'multiplier' => 4.1,
            'transit_days' => 1,
            'is_international' => false,
            'is_active' => true,
        ],
        'standard' => [
            'label' => 'Standard',
            'base_rate' => 32,
            'per_kg_rate' => 7.8,
            'multiplier' => 1.8,
            'transit_days' => 4,
            'is_international' => false,
            'is_active' => true,
        ],
        'express' => [
            'label' => 'Express',
            'base_rate' => 48,
            'per_kg_rate' => 7.8,
            'multiplier' => 2.6,
            'transit_days' => 2,
            'is_international' => false,
            'is_active' => true,
        ],
    ],

    'templates' => [
        'standard_international' => [
            'id' => 'standard_international',
            'name' => 'Standard International Shipment',
            'summary' => 'Balanced transit for cross-border commercial freight.',
            'category' => 'General Merchandise',
            'package_type' => 'Commercial Carton',
            'purpose' => 'Business',
            'service' => 'international_priority',
            'insurance' => 'standard_insurance',
            'payment_enabled' => true,
            'package_defaults' => [
                'description' => 'International merchandise',
                'weight_kg' => 18,
                'length_cm' => 48,
                'width_cm' => 40,
                'height_cm' => 36,
                'declared_value' => 1800,
            ],
            'notes' => [
                'customs_notes' => 'Shipment is pending customs review, if required.',
            ],
        ],
        'express_domestic' => [
            'id' => 'express_domestic',
            'name' => 'Express Domestic Shipment',
            'summary' => 'Fast domestic movement with minimal handling delays.',
            'category' => 'General Merchandise',
            'package_type' => 'Parcel',
            'purpose' => 'Business',
            'service' => 'express',
            'insurance' => 'standard_insurance',
            'payment_enabled' => true,
            'package_defaults' => [
                'description' => 'Domestic express parcel',
                'weight_kg' => 6,
                'length_cm' => 34,
                'width_cm' => 28,
                'height_cm' => 22,
                'declared_value' => 450,
            ],
            'notes' => [
                'delivery_notes' => 'Shipment is scheduled for priority domestic delivery after dispatch.',
            ],
        ],
        'freight' => [
            'id' => 'freight',
            'name' => 'Freight Shipment',
            'summary' => 'Heavy or palletized cargo with staged operational handling.',
            'category' => 'Freight',
            'package_type' => 'Palletized Cargo',
            'purpose' => 'Commercial',
            'service' => 'freight',
            'insurance' => 'premium_insurance',
            'payment_enabled' => true,
            'package_defaults' => [
                'description' => 'Freight cargo pallet',
                'weight_kg' => 120,
                'length_cm' => 120,
                'width_cm' => 100,
                'height_cm' => 150,
                'declared_value' => 6200,
            ],
            'notes' => [
                'warehouse_notes' => 'Awaiting freight warehouse staging and pallet verification.',
            ],
        ],
        'medical' => [
            'id' => 'medical',
            'name' => 'Medical Shipment',
            'summary' => 'Controlled handling for medical and laboratory consignments.',
            'category' => 'Medical',
            'package_type' => 'Temperature Controlled Case',
            'purpose' => 'Medical',
            'service' => 'overnight',
            'insurance' => 'premium_insurance',
            'payment_enabled' => true,
            'package_defaults' => [
                'description' => 'Medical supplies',
                'weight_kg' => 8,
                'length_cm' => 42,
                'width_cm' => 32,
                'height_cm' => 28,
                'declared_value' => 2800,
                'temperature_controlled' => true,
            ],
            'notes' => [
                'internal_shipment_notes' => 'Shipment created successfully. Awaiting pickup confirmation.',
                'pickup_instructions' => 'Package is scheduled for pickup. Please ensure it is properly packaged and ready for collection.',
                'warehouse_notes' => 'Awaiting warehouse processing.',
                'customs_notes' => 'Shipment is pending customs review, if required.',
                'delivery_notes' => 'Shipment is scheduled for delivery after all processing stages are complete.',
            ],
        ],
        'fragile' => [
            'id' => 'fragile',
            'name' => 'Fragile Shipment',
            'summary' => 'Extra care workflow for delicate goods requiring controlled handling.',
            'category' => 'Fragile Goods',
            'package_type' => 'Protected Parcel',
            'purpose' => 'Business',
            'service' => 'standard',
            'insurance' => 'premium_insurance',
            'payment_enabled' => true,
            'package_defaults' => [
                'description' => 'Fragile packaged goods',
                'weight_kg' => 10,
                'length_cm' => 44,
                'width_cm' => 38,
                'height_cm' => 30,
                'declared_value' => 1500,
                'fragile' => true,
            ],
            'notes' => [
                'warehouse_notes' => 'Awaiting warehouse processing in fragile handling lane.',
            ],
        ],
        'electronics' => [
            'id' => 'electronics',
            'name' => 'Electronics Shipment',
            'summary' => 'High-value electronics with audit-friendly traceability.',
            'category' => 'Electronics',
            'package_type' => 'Secured Carton',
            'purpose' => 'Business',
            'service' => 'express',
            'insurance' => 'premium_insurance',
            'payment_enabled' => true,
            'package_defaults' => [
                'description' => 'Electronic devices',
                'weight_kg' => 14,
                'length_cm' => 50,
                'width_cm' => 36,
                'height_cm' => 30,
                'declared_value' => 4200,
            ],
            'notes' => [
                'customer_tracking_message' => 'Your shipment has been created and is being prepared for secure electronics processing. You can monitor progress using your tracking number.',
            ],
        ],
    ],

    'warehouse_country_map' => [
        'US' => 'MEM', 'CA' => 'MEM',
        'GB' => 'LHR', 'DE' => 'LHR', 'FR' => 'LHR', 'NL' => 'LHR',
        'AE' => 'DXB', 'IN' => 'DXB', 'CN' => 'DXB', 'JP' => 'DXB', 'KR' => 'DXB', 'SG' => 'DXB',
        'NG' => 'LOS', 'ZA' => 'LOS', 'KE' => 'LOS', 'GH' => 'LOS', 'EG' => 'LOS',
        'BR' => 'GRU', 'MX' => 'GRU',
        'AU' => 'LHR',
    ],

    'currencies' => [
        ['code' => 'USD', 'label' => 'US Dollar ($)'],
        ['code' => 'EUR', 'label' => 'Euro (€)'],
        ['code' => 'GBP', 'label' => 'British Pound (£)'],
        ['code' => 'CAD', 'label' => 'Canadian Dollar (CA$)'],
        ['code' => 'NGN', 'label' => 'Nigerian Naira (₦)'],
        ['code' => 'AED', 'label' => 'UAE Dirham (د.إ)'],
        ['code' => 'INR', 'label' => 'Indian Rupee (₹)'],
        ['code' => 'JPY', 'label' => 'Japanese Yen (¥)'],
    ],
];
